name: update
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout README.md
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python update.py ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated README.md."
          git push
